[project]
name = "trees"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "networkx>=3.4.2",
    "pytest>=8.3.4",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["trees"]
